from .compile_interpreter import mcs_compile
from ..common import module_folder, COMMON_CONFIG
from ..text_additions import text_error
from os import mkdir, listdir, rmdir
from time import time
from shutil import copyfile
import os

class Compiler:
    def __init__(self, ast: list, datapack_name: str, output_path: str, verbose: bool):
        self.ast = ast
        self.datapack_name = datapack_name
        self.datapack_id = datapack_name.lower().replace(' ', '_')
        self.output_path = output_path
        self.verbose = verbose
        self.root_folder = f"{self.output_path}/{self.datapack_name}"
    def make_init_file(self):
        text = (
            "################################################################\n"
            "#                                                              #\n"
            "#  default init.mcfunction file generated by Minecraft-Script  #\n"
            "#                                                              #\n"
            "################################################################\n"
            "\n"
            "scoreboard objectives add mcs_math dummy \"Minecraft-Script Math\"\n"
            "scoreboard objectives add mcs_click minecraft.used:minecraft.carrot_on_a_stick \"Minecraft-Script Click\"\n"
            "\n"
            f"function {self.datapack_id}:user_functions/init\n"
        )
        with open(f'{self.root_folder}/data/{self.datapack_id}/function/init.mcfunction', 'xt') as init_file:
            init_file.write(text)
    def make_main_file(self):
        text = (
            "################################################################\n"
            "#                                                              #\n"
            "#  default main.mcfunction file generated by Minecraft-Script  #\n"
            "#                                                              #\n"
            "################################################################\n"
            "\n"
            f"execute as @a at @s if score @s mcs_click matches 1.. run function {self.datapack_id}:clickable_items/check\n"
            "\n"
            f"function {self.datapack_id}:user_functions/main\n"
        )
        with open(f'{self.root_folder}/data/{self.datapack_id}/function/main.mcfunction', 'xt') as main_file:
            main_file.write(text)
    def make_kill_file(self):
        text = (
            "################################################################\n"
            "#                                                              #\n"
            "#  default kill.mcfunction file generated by Minecraft-Script  #\n"
            "#                                                              #\n"
            "################################################################\n"
            "\n"
            f"function {self.datapack_id}:user_functions/kill\n"
            "\n"
            "scoreboard objectives remove mcs_math\n"
            "scoreboard objectives remove mcs_click\n"
            "data remove storage mcs_click id\n"
            "\n"
            f"datapack disable \"file/{self.datapack_name}\"\n"
        )
        with open(f'{self.root_folder}/data/{self.datapack_id}/function/kill.mcfunction', 'xt') as kill_file:
            kill_file.write(text)
    def make_click_item_check_file(self):
        check_text = (
            "scoreboard players set @s mcs_click 0\n"
            "\n"
            "data modify storage mcs_click id set from entity @s SelectedItem.components.\"minecraft:custom_data\".mcs_click\n"
            f"function {self.datapack_id}:clickable_items/run with storage mcs_click\n"
        )
        click_path = f'{self.root_folder}/data/{self.datapack_id}/function/clickable_items'
        mkdir(click_path)
        with open(f'{click_path}/check.mcfunction', 'xt') as check_file:
            check_file.write(check_text)
        with open(f'{click_path}/run.mcfunction', 'xt') as run_file:
            run_file.write(f"$function {self.datapack_id}:clickable_items/$(id)\n")
    def import_math_files(self, used_math_ops):
        if not used_math_ops:
            return
        math_folder = f'{self.root_folder}/data/{self.datapack_id}/function/math'
        mkdir(math_folder)
        source_folder = f'{module_folder}/compiler/build_templates/math'
        for filename in listdir(source_folder):
            name = filename.split('.')[0]
            if name in used_math_ops:
                copyfile(
                    f'{source_folder}/{filename}',
                    f'{math_folder}/{filename}'
                )
    def import_builtins_files(self, used_builtins):
        if not used_builtins:
            return
        builtins_folder = f'{self.root_folder}/data/{self.datapack_id}/function/builtins'
        mkdir(builtins_folder)
        source_folder = f'{module_folder}/compiler/build_templates/builtins'
        for filename in listdir(source_folder):
            name = filename.split('.')[0]
            if name in used_builtins:
                copyfile(
                    f'{source_folder}/{filename}',
                    f'{builtins_folder}/{filename}'
                )
    def import_tags_folder(self):
        module_tags_folder = f'{module_folder}/compiler/build_templates/tags'
        datapack_tags_folder = f'{self.root_folder}/data/{self.datapack_id}/tags'
        mkdir(datapack_tags_folder)
        for directory_name in listdir(module_tags_folder):
            current_module_folder = f'{module_tags_folder}/{directory_name}'
            current_datapack_folder = f'{datapack_tags_folder}/{directory_name}'
            mkdir(current_datapack_folder)
            for file_name in listdir(current_module_folder):
                copyfile(
                    f'{current_module_folder}/{file_name}',
                    f'{current_datapack_folder}/{file_name}'
                )
    def clean_empty_folder(self, folder_path):
        if os.path.exists(folder_path) and not os.listdir(folder_path):
            rmdir(folder_path)
    def generate_builtin_functions(self, used_math_ops, used_builtins):
        if self.verbose:
            print('\rBuilding built-in functions...', end="")
        self.make_init_file()
        if self.verbose:
            print('\rBuilding built-in functions... 17%', end="")
        self.make_main_file()
        if self.verbose:
            print('\rBuilding built-in functions... 33%', end="")
        self.make_kill_file()
        if self.verbose:
            print('\rBuilding built-in functions... 50%', end="")
        self.import_math_files(used_math_ops)
        self.clean_empty_folder(f'{self.root_folder}/data/{self.datapack_id}/function/math')
        if self.verbose:
            print('\rBuilding built-in functions... 67%', end="")
        self.import_builtins_files(used_builtins)
        self.clean_empty_folder(f'{self.root_folder}/data/{self.datapack_id}/function/builtins')
        if self.verbose:
            print('\rBuilding built-in functions... 83%', end="")
        self.make_click_item_check_file()
        if self.verbose:
            print('\rBuilding builtin-in functions... Done!')
    def clean_empty_code_blocks(self):
        code_blocks_folder = f'{self.root_folder}/data/{self.datapack_id}/function/code_blocks'
        if os.path.exists(code_blocks_folder) and not os.listdir(code_blocks_folder):
            rmdir(code_blocks_folder)
    def build(self):
        start_time = time()
        if self.verbose:
            print(f'Building with name "{self.datapack_name}" (id: "{self.datapack_id}")')
        try:
            mkdir(f"{self.root_folder}")
        except FileExistsError:
            print(text_error(f"Can't build file: {self.datapack_name !r} folder exists already!"))
            exit()
        mkdir(f'{self.root_folder}/data')
        if self.verbose:
            print('Creating default folders...', end=" ")
        mkdir(f'{self.root_folder}/data/minecraft')
        mkdir(f'{self.root_folder}/data/minecraft/tags')
        mkdir(f'{self.root_folder}/data/minecraft/tags/function')
        mkdir(f'{self.root_folder}/data/{self.datapack_id}')
        mkdir(f'{self.root_folder}/data/{self.datapack_id}/function')
        mkdir(f'{self.root_folder}/data/{self.datapack_id}/function/code_blocks')
        mkdir(f'{self.root_folder}/data/{self.datapack_id}/function/user_functions')
        if self.verbose:
            print('Done!')
            print('Building Templates...', end=" ")
        with (
            open(f'{module_folder}/compiler/build_templates/pack.mcmeta', 'rt') as template_file,
            open(f'{self.root_folder}/pack.mcmeta', 'xt') as output_file
        ):
            template_text = template_file.read()
            output_file.write(template_text.replace("PACK_FORMAT", COMMON_CONFIG["pack_format"]))
        copyfile(f'{module_folder}/compiler/build_templates/pack.png', f'{self.root_folder}/pack.png')
        with (
            open(f'{module_folder}/compiler/build_templates/function_tags.json', 'rt') as template_file,
            open(f'{self.root_folder}/data/minecraft/tags/function/tick.json', 'xt') as tick_file,
            open(f'{self.root_folder}/data/minecraft/tags/function/load.json', 'xt') as load_file
        ):
            template_content = template_file.read()
            tick_file.write(template_content.replace('NAME', self.datapack_id).replace('FILETYPE', 'main'))
            load_file.write(template_content.replace('NAME', self.datapack_id).replace('FILETYPE', 'init'))
        if self.verbose:
            print("Done!")
        used_math_ops, used_builtins = mcs_compile(
            self.ast,
            f'{self.root_folder}/data/{self.datapack_id}/function',
            self.datapack_id
        )
        self.generate_builtin_functions(used_math_ops, used_builtins)
        self.clean_empty_code_blocks()
        if self.verbose:
            print("Generating datapack tags...", end=" ")
        self.import_tags_folder()
        if self.verbose:
            print("Done!")
        elapsed_time = time() - start_time
        if self.verbose:
            print(f'Finished compiling {self.datapack_name}! Time Elapsed: {elapsed_time: 0.3f}s')
