org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.caching=true

mod_id=minecraft_script
mod_name=Minecraft Script
mod_version=0.1.0
mod_group=dev.spyc0der.minecraftscript
mod_license=MIT
mod_description=Compiles Minecraft-Script packs from world mcs_packs folders into datapacks.

architectury_loom_version=1.14-SNAPSHOT
architectury_plugin_version=3.4-SNAPSHOT
fabric_loader_version=0.19.3
